name: selang_seling
description: A Dart Dart library for interleaving lists, providing flexible methods to combine elements from multiple lists based on customizable item counts.
version: 1.0.1
repository: https://github.com/kakzaki/selang_seling.git

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
